//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmilyK_DDfinalproject
{
    using System;
    using System.Collections.Generic;
    
    public partial class CalendarEvent
    {
        public CalendarEvent()
        {
            this.Payments = new HashSet<Payment>();
        }
    
        public int EventId { get; set; }
        public string EventName { get; set; }
        public Nullable<System.DateTime> EventDate { get; set; }
        public Nullable<int> EventType { get; set; }
        public Nullable<int> Importance { get; set; }
        public Nullable<int> PrimaryPerson { get; set; }
        public Nullable<int> SecondaryPerson { get; set; }
        public Nullable<int> RecurringType { get; set; }
    
        public virtual EventType EventType1 { get; set; }
        public virtual Importance Importance1 { get; set; }
        public virtual Person Person { get; set; }
        public virtual Recurring Recurring { get; set; }
        public virtual Person Person1 { get; set; }
        public virtual ICollection<Payment> Payments { get; set; }
    }
}
