//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmilyK_DDfinalproject
{
    using System;
    using System.Collections.Generic;
    
    public partial class Payment
    {
        public int PaymentId { get; set; }
        public Nullable<int> EventId { get; set; }
        public Nullable<int> PaymentType { get; set; }
        public Nullable<int> PaymentAmount { get; set; }
    
        public virtual CalendarEvent CalendarEvent { get; set; }
        public virtual PaymentType PaymentType1 { get; set; }
    }
}
