//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmilyK_DDfinalproject
{
    using System;
    using System.Collections.Generic;
    
    public partial class Person
    {
        public Person()
        {
            this.CalendarEvents = new HashSet<CalendarEvent>();
            this.CalendarEvents1 = new HashSet<CalendarEvent>();
        }
    
        public int PersonId { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public Nullable<int> Relation { get; set; }
    
        public virtual ICollection<CalendarEvent> CalendarEvents { get; set; }
        public virtual ICollection<CalendarEvent> CalendarEvents1 { get; set; }
    }
}
